global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-db:5432"]
    metrics_path: '/metrics'
    params:
      sslmode: ['disable']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "postgres-db:9187"
  - job_name: "kavun"
    static_configs:
      - targets: ["host.docker.internal:8080"] # Use host.docker.internal for local app
    metrics_path: '/actuator/prometheus'