global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "kavun"
    static_configs:
      - targets: ["host.docker.internal:8080"] # Use host.docker.internal for local app
    metrics_path: '/actuator/prometheus'